# Generated by Django 5.2.9 on 2025-12-05 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('courses', '0002_comment_usernote_contentprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interactionlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional context data'),
        ),
        migrations.AddField(
            model_name='interactionlog',
            name='video_timestamp',
            field=models.FloatField(default=0.0, help_text='Position in video when interaction occurred'),
        ),
        migrations.AlterField(
            model_name='interactionlog',
            name='interaction_type',
            field=models.CharField(choices=[('view', 'View'), ('complete', 'Complete'), ('heartbeat', 'Heartbeat'), ('pause', 'Pause'), ('resume', 'Resume')], max_length=20),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('max_score', models.FloatField(default=100.0)),
                ('percentage', models.FloatField(default=0.0)),
                ('time_taken_seconds', models.FloatField(default=0.0)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='courses.contentblock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
