# Generated by Django 5.2.8 on 2025-12-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_comment_usernote_contentprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('PROGRAMMING', 'Programming'), ('WEB_DEV', 'Web Development'), ('DATA_SCIENCE', 'Data Science'), ('MACHINE_LEARNING', 'Machine Learning'), ('DESIGN', 'Design'), ('SECURITY', 'Cybersecurity'), ('MOBILE', 'Mobile Development'), ('DEVOPS', 'DevOps')], default='PROGRAMMING', max_length=30),
        ),
        migrations.AddField(
            model_name='course',
            name='difficulty',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BEGINNER', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='estimated_hours',
            field=models.PositiveIntegerField(default=10, help_text='Estimated hours to complete'),
        ),
        migrations.AddField(
            model_name='course',
            name='image_url',
            field=models.URLField(blank=True, help_text='Course thumbnail image URL', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="List of tags like ['Python', 'Backend', 'API']"),
        ),
    ]
