# Generated by Django 5.2.9 on 2025-12-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studentprofile_badges_earned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='average_quiz_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='resources_visited_count',
            field=models.IntegerField(default=0),
        ),
    ]
